/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkDepthOfFieldPassFS string.
 *
 */
#ifndef vtkDepthOfFieldPassFS_h
#define vtkDepthOfFieldPassFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkDepthOfFieldPassFS;

#endif /* #ifndef vtkDepthOfFieldPassFS_h */
