/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkDepthPeelingPassFinalFS string.
 *
 */
#ifndef vtkDepthPeelingPassFinalFS_h
#define vtkDepthPeelingPassFinalFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkDepthPeelingPassFinalFS;

#endif /* #ifndef vtkDepthPeelingPassFinalFS_h */
