/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkDepthPeelingPassIntermediateFS string.
 *
 */
#ifndef vtkDepthPeelingPassIntermediateFS_h
#define vtkDepthPeelingPassIntermediateFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkDepthPeelingPassIntermediateFS;

#endif /* #ifndef vtkDepthPeelingPassIntermediateFS_h */
