/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkEDLShadeFS string.
 *
 */
#ifndef vtkEDLShadeFS_h
#define vtkEDLShadeFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkEDLShadeFS;

#endif /* #ifndef vtkEDLShadeFS_h */
