/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkEDLComposeFS string.
 *
 */
#ifndef vtkEDLComposeFS_h
#define vtkEDLComposeFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkEDLComposeFS;

#endif /* #ifndef vtkEDLComposeFS_h */
