/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkGlyph3DVS string.
 *
 */
#ifndef vtkGlyph3DVS_h
#define vtkGlyph3DVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkGlyph3DVS;

#endif /* #ifndef vtkGlyph3DVS_h */
