/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkGaussianBlurPassFS string.
 *
 */
#ifndef vtkGaussianBlurPassFS_h
#define vtkGaussianBlurPassFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkGaussianBlurPassFS;

#endif /* #ifndef vtkGaussianBlurPassFS_h */
