/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkGaussianBlurPassVS string.
 *
 */
#ifndef vtkGaussianBlurPassVS_h
#define vtkGaussianBlurPassVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkGaussianBlurPassVS;

#endif /* #ifndef vtkGaussianBlurPassVS_h */
