/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkPolyDataWideLineGS string.
 *
 */
#ifndef vtkPolyDataWideLineGS_h
#define vtkPolyDataWideLineGS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPolyDataWideLineGS;

#endif /* #ifndef vtkPolyDataWideLineGS_h */
