/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkPolyDataVS string.
 *
 */
#ifndef vtkPolyDataVS_h
#define vtkPolyDataVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPolyDataVS;

#endif /* #ifndef vtkPolyDataVS_h */
