/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkPolyData2DFS string.
 *
 */
#ifndef vtkPolyData2DFS_h
#define vtkPolyData2DFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPolyData2DFS;

#endif /* #ifndef vtkPolyData2DFS_h */
