/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkPointFillPassFS string.
 *
 */
#ifndef vtkPointFillPassFS_h
#define vtkPointFillPassFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPointFillPassFS;

#endif /* #ifndef vtkPointFillPassFS_h */
