/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkStickMapperVS string.
 *
 */
#ifndef vtkStickMapperVS_h
#define vtkStickMapperVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkStickMapperVS;

#endif /* #ifndef vtkStickMapperVS_h */
