/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkSimpleMotionBlurPassFS string.
 *
 */
#ifndef vtkSimpleMotionBlurPassFS_h
#define vtkSimpleMotionBlurPassFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkSimpleMotionBlurPassFS;

#endif /* #ifndef vtkSimpleMotionBlurPassFS_h */
