/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkSSAAPassFS string.
 *
 */
#ifndef vtkSSAAPassFS_h
#define vtkSSAAPassFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkSSAAPassFS;

#endif /* #ifndef vtkSSAAPassFS_h */
