/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkSobelGradientMagnitudePass1FS string.
 *
 */
#ifndef vtkSobelGradientMagnitudePass1FS_h
#define vtkSobelGradientMagnitudePass1FS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkSobelGradientMagnitudePass1FS;

#endif /* #ifndef vtkSobelGradientMagnitudePass1FS_h */
