/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-9.0
 * 
 * Declare the vtkSphereMapperVS string.
 *
 */
#ifndef vtkSphereMapperVS_h
#define vtkSphereMapperVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkSphereMapperVS;

#endif /* #ifndef vtkSphereMapperVS_h */
